### ISSUE TITLE
How to use @lihbr/utils-nuxt.head alongside vue-meta's per-page script array?

### ISSUE THREAD

**Issue by inlikealion** [lihbr/utils-nuxt#3]
`utils-nuxt.head` offers tons of configuration our Nuxt project would benefit from. However, I'm not sure how to use it with other `head() {}` functions on per-page instances like a vanilla Nuxt project. I want to still be able to add scripts or portions of `vue-meta`'s `head` function that are NOT covered by `utils-nuxt.head` meta and structured data.

Ex: how to use:

```
  head() {
    return this.$buildHead({
      title: "Home",
      description: "Welcome to My Company home page",
      metaImage: {
        og: "https://example.com/home-1200x630.jpg",
        tw: "https://example.com/home-1200x600.jpg"
      },
      path: this.$route.path,
      additionalStructuredData: []
    });
  }
```
alongside page-level 3rd party script declarations:
```
head() {
  return {
      script: [
        {
          type: 'text/javascript',
          src: 'https://example.com/3rd-party-script.js',
          async: true
        }
      ]
    }
}
```

Any guidance would be appreciated! Thank you for making this public.

**Comment by lihbr** [comment]
Hey, great question! First of all, I'm sorry for not maintaining this package _a lot_ (Well, I do maintain it and I use it on production so if I come across any bug I'll fix it ^^') Anyway!

With `@lihbr/utils-nuxt.head` the injected `$buildHead` function returns a valid Vue Meta object.
From here you're free to alter it to add or remove things from it.
For example to merge your above examples it'll go like this:

```javascript
export default {
  head() {
    const head = this.$buildHead({
      title: "Home",
      description: "Welcome to My Company home page",
      metaImage: {
        og: "https://example.com/home-1200x630.jpg",
        tw: "https://example.com/home-1200x600.jpg"
      },
      path: this.$route.path,
      additionalStructuredData: []
    });

    head.script.push(
      {
        type: 'text/javascript',
        src: 'https://example.com/3rd-party-script.js',
        async: true
      }
    );

    return head;
  }
}
```

I hope that answers your question ☺️, let me know if you need further details! Cheer~

**Comment by inlikealion** [comment]
Hmm… I've attempted this but the `head.scrpt.push()` function doesn't result in the script being added to `<head>` as when using the traditional vue-meta `head()` function. This is on a dynamic page several layers deep in `pages/products/.../_productId.vue`. The `head = this.$buildHead()` block IS correctly affecting the rendered page output.

**Comment by lihbr** [comment]
Okay, indeed there was a typo in my example, you cannot push an array to the script array (or you have to spread it before) 🙈

Updated my example above (basically just pushing the object now), tested on my website, works as expected :)

**Comment by inlikealion** [comment]
Lucie thanks for the catch! I wouldn't have caught that restriction on pushing arrays. This worked perfectly and now I'm up and running with Schema, meta data, and our page-level scripts. Cheers!

**Comment by lihbr** [comment]
Awesome! Have a great week ☺️
